name: My actions have consequence

on: [push]

jobs:
  ega:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Set up Chromedriver
        uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: '135.0.7049.84'

      - name: Start X virtual framebuffer
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pytest

      - name: Run run_test.py
        run: |
          export DISPLAY=:99
          export PYTHONPATH="${{ github.workspace }}"
          python run_test.py

      - name: Run Pytest
        run: |
          export DISPLAY=:99
          export PYTHONPATH="${{ github.workspace }}"
          pytest

      - name: Success message
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
